### ISSUE TITLE
breaks css calc operator

### ISSUE THREAD

**Issue by brianmay** [rspivak/slimit#67]
slimit will translate the following css:

``` css
.module table {                                                                  
    width: 99%;                                                                  
    width: calc(100% - 8px);                                                     
}
```

into:

``` css
.module table{width:calc(100%-8px);}
```

Which, unfortunately, is broken because the '-' operator must be separated by white space, or the entire item will be considered invalid.

Not only that, it also removed my fall back option (99%), in case the browser doesn't support the calc operator.
